apiVersion: v1
kind: Service
metadata:
  name: ms-pagamento-nodeport
  namespace: fiapeats-hk
spec:
  selector:
    app: ms-pagamento
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30083
  type: NodePort