apiVersion: v1
kind: Service
metadata:
  name: ms-pagamento-cluster
  namespace: fiapeats-hk
spec:
  selector:
    app: ms-produto
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
