apiVersion: v1
kind: Service
metadata:
  name: ms-pedido-nodeport
  namespace: fiapeats-hk
spec:
  selector:
    app: ms-pedido
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort