apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-cliente-deployment
  namespace: fiapeats-hk
  labels:
    app: ms-cliente
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-cliente
  template:
    metadata:
      labels:
        app: ms-cliente
    spec:
      containers:
        - name: ms-cliente-container
          image: dilanclima/ms-cliente:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: ms-cliente.username
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: ms-cliente.url
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: ms-cliente.password
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /mscliente/actuator/health
              port: 8080
            initialDelaySeconds: 105
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /mscliente/actuator/health
              port: 8080
            initialDelaySeconds: 105
            periodSeconds: 10
      restartPolicy: Always
