apiVersion: v1
kind: Service
metadata:
  name: ms-cliente-cluster
  namespace: fiapeats-hk
spec:
  selector:
    app: ms-cliente
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
