apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fiapeats-api-hpa
  namespace: fiapeats-hk
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fiapeats-api-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80